USE FIRM;

SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE Citizen;
TRUNCATE TABLE Station;
TRUNCATE TABLE Permission;
TRUNCATE TABLE User;
TRUNCATE TABLE Officer;
TRUNCATE TABLE Fir;
TRUNCATE TABLE Court;
TRUNCATE TABLE Cases;
TRUNCATE TABLE Suspect;
